### ISSUE TITLE
v6: modernize codebase/tests/docs with use of async function

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/sequelize#11859]
**To-do**

- [ ] refactor/docs
- [ ] refactor/integration/tests
- [ ] refactor/unit/tests
- [ ] refactor/lib/extra files, helpers (non core stuff)
- [ ] refactor/lib/dialects/abstract
- [ ] refactor/lib/dialects/mssql
- [ ] refactor/lib/dialects/mariadb
- [ ] refactor/lib/dialects/mysql
- [ ] refactor/lib/dialects/sqlite
- [ ] refactor/lib/dialects/postgres
- [ ] refactor/lib/transaction
- [ ] refactor/lib/associations
- [ ] refactor/lib/queryInterface
- [ ] refactor/lib/sequelize
- [ ] refactor/lib/model
- [ ] refactor/lib/anything else

**Verify**

- [ ] docs
- [ ] code
- [ ] tests

**Comment by papb** [comment]
Docs already use `async` everywhere after my PR :)

**Comment by jedwards1211** [comment]
I do assume that the plan is to stop using Bluebird-specific functions with async/await right?  Because `Promise`s returned by `async` methods won't have Bluebird methods on them unless we overwrite `Promise` globally...

**Comment by sushantdhiman** [comment]
Yes with async await we no longer need to use Bluebird, so removing Bluebird is the first step in this modernization effort

**Comment by sushantdhiman** [comment]
I think `async` conversion is complete now, so closing this issue. Thank you @jedwards1211 for this great refactor

**Comment by jedwards1211** [comment]
Thanks for your hard work maintaining Sequelize!

**Comment by papb** [comment]
Thank you very much @jedwards1211 !!

**Comment by jedwards1211** [comment]
My pleasure!
Is there an issue somewhere with details how you all want to convert to ES modules?
That's something I could do pretty quickly with jscodeshift as well

**Comment by papb** [comment]
@jedwards1211 I personally still prefer CommonJS style for now... I think the next big conversion can be to TypeScript, no need for an intermediate conversion to ES modules in my opinion.
