### ISSUE TITLE
Difference between add[MODEL] and create[MODEL] magic methods of sequelize

### ISSUE THREAD

**Issue by tbhaxor** [sequelize/sequelize#12048]
### What was unclear/insufficient/not covered in the documentation

Difference between add[MODEL] and create[MODEL] magic methods of sequelize

### If possible: Provide some suggestion on how we can enhance the docs

There is no documentation related to the magic function. There are only names of the magic function, not the options and values they take. Also what they do.

### Additional context

**todo.js**
```js
import sequelize from './index';
import { INTEGER, STRING } from 'sequelize';

export default sequelize.define('todos', {
  id: { type: INTEGER, autoIncrement: true, primaryKey: true },
  title: STRING,
  description: STRING,
});
```

**item.js**
```js
import sequelize from './index';
import { INTEGER, STRING, BOOLEAN } from 'sequelize';

export default sequelize.define('items', {
  id: { type: INTEGER, autoIncrement: true, primaryKey: true },
  title: STRING,
  isCompleted: { type: BOOLEAN, defaultValue: false },
});
```

In **index.js**, the association looks like this
```
Todo.hasMany(Item);
Item.belongsTo(Todo, { onDelete: 'CASCADE' });
```
### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by rahulramsaha** [comment]
I've been looking for the same thing and from what i've seen, it looks like :
- Create will quite literally create an instance of the targetted model and do the association altogether 
- Add will create the association between the instance of the souce model and the instance of the target model

I am not 100% sure of that, but i believe it works this way.

**Create**
```
const todo = Todo.create ({ ... });
todo.createItem({ tite: " item 1" }); //creates the item and does the corresponding association
```

**Add**
```
const todo = Todo.create ({ ... });
const item = Item.create({ title : " item2" });
todo.addItem( item, item.id ); // does the association for an existing item
```

`

**Comment by sushantdhiman** [comment]
[`BelongsToMany.add`](https://sequelize.org/master/class/lib/associations/belongs-to-many.js~BelongsToMany.html#instance-method-add) & [`BelongsToMany.create`](https://sequelize.org/master/class/lib/associations/belongs-to-many.js~BelongsToMany.html#instance-method-create)

**Comment by tbhaxor** [comment]
> [`BelongsToMany.add`](https://sequelize.org/master/class/lib/associations/belongs-to-many.js~BelongsToMany.html#instance-method-add) & [`BelongsToMany.create`](https://sequelize.org/master/class/lib/associations/belongs-to-many.js~BelongsToMany.html#instance-method-create)

What does that mean?
