### ISSUE TITLE
When benchmark is set, the log statement "Executing query" that is called before it runs is skipped

### ISSUE THREAD

**Issue by rdsedmundo** [sequelize/sequelize#15798]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### Describe the feature you'd like to see implemented

Even when `benchmark` option is active, it's still useful to have a log of before a query will start executing, this helps quickly discovering long-running / slow queries.

https://github.com/sequelize/sequelize/blob/f16919768e8f357e5323051068202b2520cd0274/packages/core/src/dialects/abstract/query.js#L378-L389

If it's a breaking change, then we could introduce another option that would override the current behavior.

### Describe why you would like this feature to be added to Sequelize

Explained above.

### Is this feature dialect-specific?

- [x] No. This feature is relevant to Sequelize as a whole.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in implementing my feature.

---

*Indicate your interest in the addition of this feature by adding the 👍 reaction. Comments such as "+1" will be removed.*

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by ephys** [comment]
Is your request to make it execute both Executing & Executed, or is it to make them go through `sequelize.log`

If the format: I think without benchmark, it does not make sense to log both. If you're trying to discover long running queries, enable the benchmark option

If the latter: This is planned. All logs will eventually go through `sequelize.log` in the logging overhaul
