### ISSUE TITLE
Enhancement: Add SSL Option to dialectOptions

### ISSUE THREAD

**Issue by prathameshmhatre** [sequelize/sequelize#16444]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### Describe the feature you'd like to see implemented

I'd like to propose an enhancement to the Sequelize library by adding an SSL option within the dialectOptions of the configuration. This addition would allow for easier SSL connection setups, particularly when working with AWS RDS instances that require SSL connections.

### Describe why you would like this feature to be added to Sequelize
**Use Case:**
Currently, when using Sequelize with AWS RDS, establishing an SSL connection involves adding specific SSL options to the dialectOptions field. However, the current typings of dialectOptions in Sequelize don't accommodate this scenario. By adding an ssl property to dialectOptions, users would be able to easily configure SSL connections without resorting to workarounds.

**Current Behavior:**
As of now, the dialectOptions interface within Sequelize only includes charset and timeout properties. This limited configuration prevents users from conveniently enabling SSL connections with databases that require it.

**Expected Behavior:**
I suggest extending the dialectOptions interface to include an ssl property, allowing users to define SSL-related options directly within the Sequelize configuration. Here's how the enhanced interface could look:

`interface DialectOptions {
  charset?: string;
  timeout?: number;
  ssl?: {
    require?: boolean;
    // Other SSL options...
  };
}`

**Example Usage:**

`const sequelize = new Sequelize({
  dialect: 'postgres',
  port,
  host,
  database,
  username,
  password,
  dialectOptions: {
    ssl: {
     require: true
    }
  }
});`

**Environment:**

- Sequelize Version : 6.32.1
- Node.js Version : v18.16.0

### Is this feature dialect-specific?

- [ ] No. This feature is relevant to Sequelize as a whole.
- [x] Yes. This feature only applies to the following dialect(s): PostgreSql

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in implementing my feature.

---

*Indicate your interest in the addition of this feature by adding the 👍 reaction. Comments such as "+1" will be removed.*

```[tasklist]
### Tasks
```

**Comment by ephys** [comment]
Dialect options will be removed as part of #13722, and will instead of merged with the other options. Their typing will be handled based on which dialect is being used

**Comment by ephys** [comment]
Starting with [Sequelize 7 alpha 40](https://github.com/sequelize/sequelize/releases/tag/v7.0.0-alpha.40), the option bag are typed in a way that includes the options accepted by `pg`
