### ISSUE TITLE
JSONB

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#3471]
### Tasks
- [x] [Query API design](https://gist.github.com/mickhansen/7a3a85433557244e17a2)
- [x] [Index API design](https://gist.github.com/mickhansen/966a67648c45dd5c25ee)
- [x] insert/update/read support and tests
- [x] [query api integration and tests](https://github.com/sequelize/sequelize/commit/7feb5f5ee5727961355e0bdf9de11ca20d4fce8a)
- [x] [index api integration and tests](https://github.com/sequelize/sequelize/commit/315b4cf733981b665e7ef082f79f5f18863d301e)
- [x] Tests and fixes for casting for querying against integers or null values.
- [x] manual casting support
- [x] automatic casting for numbers and dates + tests
- [x] .changed() fix https://github.com/sequelize/sequelize/issues/2863 [PR](https://github.com/sequelize/sequelize/pull/3588)
- [x] Query documentation
- [x] Index documentation

**Comment by pauliusuza** [comment]
[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=10566356)](https://www.bountysource.com/issues/10566356-jsonb?utm_source=10566356&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by janmeier** [comment]
@pauliusuza Do you want to provide input to the query API design? Anything special about your usecase? Which operators _need_ to be supported for the feature to be usefull / easy to use for you?

**Comment by BridgeAR** [comment]
I'll fix .changed soon.

**Comment by pauliusuza** [comment]
I think your proposal for the Query API so far looks very good. We will try to come up with some extra use cases to validate it and see if anything breaks. Thanks!

**Comment by mickhansen** [comment]
@pauliusuza sounds good

**Comment by mickhansen** [comment]
@BridgeAR I'm beginning work on the `changed()` change, just fyi.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/pull/3588

**Comment by mickhansen** [comment]
JSONB implemented and released in 2.1.0.
@pauliusuza Please open new issues for specific changes or fixes to JSONB. I'll make sure they are fixed quickly for the next forseeable time.

**Comment by fixe** [comment]
Awesome, thanks.

**Comment by pauliusuza** [comment]
Once again, great work. Please update the live version of documentation when you have a chance. Also it might be a good idea to highlight the change on the Readme.md and link it to the relevant section in the docs.
