### ISSUE TITLE
Scopes refactor

### ISSUE THREAD

**Issue by janmeier** [sequelize/sequelize#3486]
This issue is meant to track everything that should be covered by a new / refactored scope implementation. I'm going to close the other issues so we can track everything in one place

Implementation details
- [x] Simplify implementation - no smart where
- [x] Make sure it works without default scope https://github.com/sequelize/sequelize/issues/3001 and https://github.com/sequelize/sequelize/issues/2408
- [x] Ensure columns are properly scoped https://github.com/sequelize/sequelize/pull/3315, https://github.com/sequelize/sequelize/issues/3123 and https://github.com/sequelize/sequelize/issues/2037. E.g `model.id` instead of `id`
- [x] Apply default scope along with other scopes https://github.com/sequelize/sequelize/issues/2529
- [x] Scoped models should be reusable https://github.com/sequelize/sequelize/issues/2738
- [x] Make sure it works with paranoid https://github.com/sequelize/sequelize/issues/2407
- [x] Make sure scopes work across assocations
- [x] Support includes in scopes https://github.com/sequelize/sequelize/issues/1873 and https://github.com/sequelize/sequelize/issues/3056
- [x] Support attributes, limit, offset etc.
- [x] Support passing a scoped model to include https://github.com/sequelize/sequelize/issues/1873
- [x] Documentation
  - [x] Scopes in general
  - [x] Associations between scoped models
  - [x] Association scopes
- [x] Make sure $and etc work in scopes https://github.com/sequelize/sequelize/issues/2532
- [x] Should work for count and findAndCount

Discussion points
- [ ] What should happen if both scope and find specify the attribute? `$and` or overwrite? 
- [ ] Should scopes work across associations (see https://github.com/sequelize/sequelize/issues/3005). Specifically, should default scope be applied to X for `getX`?
- [ ] Should `.scope` override or merge with the default scope?

**Comment by janmeier** [comment]
pong @sequelize/owners + @overlookmotel @cusspvz @BridgeAR

**Comment by mickhansen** [comment]
> What should happen if both scope and find specify the attribute? $and or overwrite?
Overwrite

> Should scopes work across associations (see #3005). Specifically, should default scope be applied to X for getX?
I'm not sure honestly, i would likely say yes since i assume usually people would use defaultScope for stuff like `active: true` which would always make sense.

> Should .scope override or merge with the default scope?
Override, i think.

I generally lean towards override since it's easier to reason about, what's the current way? Nothing?

**Comment by janmeier** [comment]
Current behaviour for `.scope` is override and i tend to lean towards keeping that. We'd just need a way to enable defaultScope + scope

Perhaps `.scope('somescope', { defaultScope: true })` and then prevent the key `defualtScope` in the scope object

**Comment by cusspvz** [comment]
I had written a small "clone" of sequelize API methodology into our client side entirely from scratch, that made me wonder how you built it and how I could improve it, and probably I would expose it as Open-Source as soon our **requirehit** project goes into a *production-ready* state. While I was developing `scope` feature, i've supported it not only on `Model`s but also on `Instance`s.

You may wonder why i've added them on `Instances`. I don't quite believe that *rows* or * instances* could be independent of their other references, because you must share entire changes on memory as you know them to decrease memory usage and processing needs, so the basic principle of scoping `Instances` was for `previousDataValues` sharing. While implementing them I got lot of troubles, since i was using prototype inheritance, with methods placing variables on scopes instead of original object.

So, on each scope, I ended up creating a non-writable variable: `__source__`. (In fact, I've created two because i needed to share events between them, but you don't have events here so...)
Each scope knows its prototype parent (`__proto__`) and the real source (`__source__`) and that fixed almost all my inheritance problems within `Instance` prototype methods, by simply assigning `var self = this.__source__;`, that also means **"original"** object should also have **__source__** assigned as a circular variable.

I'm not familiarized with known `scopes` issues but I'm pretty sure this could help you in some way.

Also, and inspite this subject is half off-topic, IMHO you should prototype all options and related objects on model scoping, cloning them isn't really a good idea.

**Comment by janmeier** [comment]
I'm not sure adding scopes to instances is a good idea for sequelize right now. Yes, it would be a good idea to do some caching, but it would take a lot of work, and often it is easier to implement something more concrete in userland instead of something very abstract that will work for everything in sequelize.

Scopes use prototype inheritance (the scoped object is created by `Object.create(this)`) and I'm pretty sure we are going to continue doing so

**Comment by janmeier** [comment]
I just had another thought - should scopes also work for other model methods? (`.update`, `destroy`) etc?

Not necessarily in this rewrite, but at some point

**Comment by cusspvz** [comment]
hey @janmeier !!

I wasn't proposing an implementation, just sharing my latest experience so we can fix major `scopes` issues.

Happens that most of problems I've been trough are similar to those I've seen on issues related by you.
Instead of using `.scopeObj` for sharing properties between scopes, my proposal was to use the same method I've used on our `Instance` scoping.

That consists on a regular use of `Object.create( parentModel )` but also a definition of `__source__`, with that configuration, you could scope of scopes and always knowing the source.


such as:
```
function Model () {
  this.__source__ = this;
}

Model.prototype.scope  = function () {
  var scoped = Object.create( this );
  scoped.__source__ = this.__source__;

  // here you can define directly things such as you are defining ATM
  // ...
}

// With this case example
var source = new Model(),
      scopeFromSource = source.scope(),
      scopeFromScope = scopeFromSource.scope();

Model.prototype.findAll = function () {
  var self = this,
        source = this.__source__;

  // You would have always access into scope, scope's parent and scope's root/ main source.

}

```

**Comment by cusspvz** [comment]
> I just had another thought - should scopes also work for other model methods? (.update, destroy) etc?

Since you're transposing options from Sequelize Constructor's options object on most used methods, wouldn't be a bad idea to have the feature of gathering also from the scope for each kind of method.

**Comment by sdepold** [comment]
I'm always more than surprised by how fast you guys are working! You rock hard :)

**Comment by RSSGergelyMunkacsy** [comment]
May I have a question about the new scope refactor?
I wanna set an automatically association for defaultScope (Users has a profile image).
If I set 
```
defaultScope: {
      include: [{ all: true }]
    },
```
for User, I get the following error:
```
Unhandled rejection TypeError: Object Image has no method 'getTableName'
    at module.exports.validateIncludedElement (/Users/festo/Projects/****/node_modules/sequelize/lib/model.js:2036:30)
    at module.exports.validateIncludedElements (/Users/festo/Projects/****/node_modules/sequelize/lib/model.js:1999:63)
    at null.<anonymous> (/Users/festo/Projects/****/node_modules/sequelize/lib/model.js:717:36)
    at null.<anonymous> (/Users/festo/Projects/****/node_modules/continuation-local-storage/context.js:74:17)
    at tryCatcher (/Users/festo/Projects/****/node_modules/sequelize/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/festo/Projects/****/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/festo/Projects/****/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:530:18)
    at Async._drainQueue (/Users/festo/Projects/****/node_modules/sequelize/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/Users/festo/Projects/****/node_modules/sequelize/node_modules/bluebird/js/main/async.js:187:10)
    at Async.drainQueues (/Users/festo/Projects/****/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback [as _tickCallback] (node.js:463:13)
```

**Comment by janmeier** [comment]
@RSSGergelyMunkacsy Please open a new issue, including your models and associations

**Comment by RSSGergelyMunkacsy** [comment]
Ok @janmeier, I created it: #3690
