### ISSUE TITLE
Better raw query support

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#5685]
It should be possible to write custom join queries in raw sql and still map back to SQL rather easily.
## Todo
- [ ] Use `fieldMap` to map from field name to attribute name instead of relying on SQL `as`
- [ ] Provide helper to generate `fieldMap` from findOptions
- [ ] Use `fieldMap` in regular findAll
- [ ] Parse includes
## Unresolved
- [ ] Should `fieldMap` be `columnMap` instead?
