### ISSUE TITLE
discuss "setter" property functionality ... when (not) to call them?

### ISSUE THREAD

**Issue by iamjochem** [sequelize/sequelize#675]
I wrote the getter/setter functionality that was recently merged ... I have a open PR for documentation thereof (see https://github.com/sequelize/sequelize-doc/pull/46) ...  writing the documentation text got me think about "setters" and when they should and should not be called ... so I a couple of questions:
-   should setters be triggered when using Model.build() ? should this be a configuration option? (if 'yes' what should the default be?)
-    should setters be triggered when a model instance is created by the DAOFactory from an existing database recoerd? should this be a configuration option? (if 'yes' what should the default be?)
-   should there be an explicit method (e.g. instance.setRawData({name: 'JOCHEM', 'age': -36})) for setting data on a model instance by which setters can be circumvented?
-  should custom setters and getters be allowed  for "default" (e.g. id, createdAt, updatedAt, etc) fields (or not)? if not do we silently ignore the custom definitions or throw an Error in `model.define()`?

currently setters are always triggered when data is put into a model instance (be it by building a new instance or when an instance is generated from an existing DB record). 
##  **Action Plan**
1. [ ] discuss our possibilities, requirements, preferences.
2. [ ] decide on what/how we want it to work
3. [ ] write user documentation describing the intended functionality
4. [ ] write tests to validate the intended functionality
5. [ ] write code to fix/implement failing tests?

**Comment by svenlombaert** [comment]
This got closed without any explanation? Is something like this already possible? The docs don't give me a lot of extra info tbh.
