### ISSUE TITLE
State of the Union

### ISSUE THREAD

**Issue by durango** [sequelize/sequelize#749]
Just a general todo list for [sequelizejs](https://github.com/sequelize/sequelize) in no particular order whatsoever. Feel free to comment on any of these issues or submit a pull request. I'm usually pretty busy, but every now and then I usually don't mind upgrading the tools I use everyday. Any kind of contribution is welcomed.
# Doc Changes
- [x] Write about the new scope functionality
- [x] https://github.com/sequelize/sequelize/pull/716 - write about eagerloading/saving
- [x] https://github.com/sequelize/sequelize/pull/728 - explicit migrations
- [x] https://github.com/sequelize/sequelize/pull/698 -M2M custom table names
- [x] https://github.com/sequelize/sequelize/pull/743
- [x] QueryOptions
- [x] https://github.com/sequelize/sequelize/pull/626 - promises
- [x] https://github.com/sequelize/sequelize/pull/648 - make sure noted in doc...
- [x] hstore
- [x] https://github.com/sequelize/sequelize/pull/597/files - paranoid
- [x] https://github.com/sequelize/sequelize/pull/569 - bulks
- [ ] https://github.com/sequelize/sequelize/pull/567 up/down migrations
- [ ] https://github.com/sequelize/sequelize/pull/564 - schematic
- [x] https://github.com/sequelize/sequelize/pull/527/files - deleteAll??
- [ ] https://github.com/sequelize/sequelize/pull/525/files - filesFilter/migrations
- [x] https://github.com/sequelize/sequelize/pull/483 - reload
- [x] https://github.com/sequelize/sequelize/pull/477/files - array groups
- [x] https://github.com/sequelize/sequelize/issues/722  async validations in 2.0.0
- [x] BIG: Write an entire manual for Sequelize (write about the internals, how everything works with each other, etc)
- [ ] Document the fact that everything is saved in UTC [#854](https://github.com/sequelize/sequelize/issues/854)
# General TODO
- [ ] Profile sequelizejs and figure out where the slow points are (especially for large datasets)
- [x] multiple primary keys
- [x] multiple unique keys
- [x] multiple index keys (smart sorting on the where object too)
- [x] https://github.com/sequelize/sequelize/pull/651#issuecomment-19383059 - bug?
- [ ] add "fake" hstore support for mysql/sqlite3
- [ ] add "fake" array support for mysql/sqlite3
- [x] code clean up/sweep!
- [ ] method support
- [x] https://github.com/sequelize/sequelize/pull/523 -- add buster test + docs
- [x] https://github.com/sequelize/sequelize/pull/457 updates some fields only -- tests + docs
- [ ] migrations up/down/tests-up/tests-down
- [x] enable ENV for spec tests
- [x] Add binary tests using bats or something similar.
- [x] Add support for handling with arrays, enums, etc. within the smartWhere Object
- [x] Convert all jasmine tests over to buster
- [x] Transactions
- [x] Support for update of tables without primary key
- [x] MariaDB support
- [x] Eager loading of nested associations #388
- [x] Move validation of enum attribute value to validate method
- [x] BLOB #99 
- [ ] I'd really like to make a plugins/middleware system for transactions + paging amongst other things
- [ ] Look a the sanitation of ordering
- [ ] Make it possible to extend pre-defined datatypes. Something along the lines of `.bud` in #904
